// <auto-generated />
using System;
using LogicaAccesoDatos.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LogicaAccesoDatos.Migrations
{
    [DbContext(typeof(LibreriaContext))]
    partial class LibreriaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LogicaNegocio.Entidades.Agencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Agencias");

                    b.HasData(
                        new
                        {
                            Id = 1
                        },
                        new
                        {
                            Id = 2
                        });
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.Envios.Envio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("ClienteId");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int")
                        .HasColumnName("EmpleadoId");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaCreacion");

                    b.Property<DateTime?>("FechaFinalizacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("FechaFinalizacion");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EmpleadoId");

                    b.ToTable("Envios", (string)null);

                    b.HasDiscriminator().HasValue("Envio");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.EtapaSeguimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<int>("IdEnvio")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdEmpleado");

                    b.HasIndex("IdEnvio");

                    b.ToTable("EtapasSeguimiento", (string)null);
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.Usuarios.Usuario.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);

                    b.HasDiscriminator().HasValue("Usuario");

                    b.UseTphMappingStrategy();

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Discriminator = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Discriminator = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            Discriminator = "Cliente"
                        },
                        new
                        {
                            Id = 4,
                            Discriminator = "Cliente"
                        });
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.Envios.Comun", b =>
                {
                    b.HasBaseType("LogicaNegocio.Entidades.Envios.Envio");

                    b.Property<int>("LugarRetiroId")
                        .HasColumnType("int")
                        .HasColumnName("LugarRetiroId");

                    b.HasIndex("LugarRetiroId");

                    b.HasDiscriminator().HasValue("Comun");
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.Envios.Urgente", b =>
                {
                    b.HasBaseType("LogicaNegocio.Entidades.Envios.Envio");

                    b.HasDiscriminator().HasValue("Urgente");
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.Usuarios.Usuario.Cliente", b =>
                {
                    b.HasBaseType("LogicaNegocio.Entidades.Usuarios.Usuario.Usuario");

                    b.HasDiscriminator().HasValue("Cliente");
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.Usuarios.Usuario.Empleado", b =>
                {
                    b.HasBaseType("LogicaNegocio.Entidades.Usuarios.Usuario.Usuario");

                    b.HasDiscriminator().HasValue("Empleado");
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.Usuarios.Empleados.Administrador", b =>
                {
                    b.HasBaseType("LogicaNegocio.Entidades.Usuarios.Usuario.Empleado");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.Usuarios.Empleados.Funcionario", b =>
                {
                    b.HasBaseType("LogicaNegocio.Entidades.Usuarios.Usuario.Empleado");

                    b.HasDiscriminator().HasValue("Funcionario");
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.Agencia", b =>
                {
                    b.OwnsOne("LogicaNegocio.Vo.Agencia.DireccionPostal", "DireccionPostal", b1 =>
                        {
                            b1.Property<int>("AgenciaId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("DireccionPostal");

                            b1.HasKey("AgenciaId");

                            b1.ToTable("Agencias");

                            b1.WithOwner()
                                .HasForeignKey("AgenciaId");

                            b1.HasData(
                                new
                                {
                                    AgenciaId = 1,
                                    Value = "Av. Principal 123"
                                },
                                new
                                {
                                    AgenciaId = 2,
                                    Value = "Calle Secundaria 456"
                                });
                        });

                    b.OwnsOne("LogicaNegocio.Vo.Usuario.Nombre", "Nombre", b1 =>
                        {
                            b1.Property<int>("AgenciaId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Nombre");

                            b1.HasKey("AgenciaId");

                            b1.ToTable("Agencias");

                            b1.WithOwner()
                                .HasForeignKey("AgenciaId");

                            b1.HasData(
                                new
                                {
                                    AgenciaId = 1,
                                    Value = "Agencia San Ramón"
                                },
                                new
                                {
                                    AgenciaId = 2,
                                    Value = "Agencia Montevideo"
                                });
                        });

                    b.OwnsOne("LogicaNegocio.Vo.Agencia.Ubicacion", "Ubicacion", b1 =>
                        {
                            b1.Property<int>("AgenciaId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Latitud")
                                .HasPrecision(9, 6)
                                .HasColumnType("decimal(9,6)")
                                .HasColumnName("Latitud");

                            b1.Property<decimal>("Longitud")
                                .HasPrecision(9, 6)
                                .HasColumnType("decimal(9,6)")
                                .HasColumnName("Longitud");

                            b1.HasKey("AgenciaId");

                            b1.ToTable("Agencias");

                            b1.WithOwner()
                                .HasForeignKey("AgenciaId");

                            b1.HasData(
                                new
                                {
                                    AgenciaId = 1,
                                    Latitud = -34.9011m,
                                    Longitud = -56.1645m
                                },
                                new
                                {
                                    AgenciaId = 2,
                                    Latitud = -34.9050m,
                                    Longitud = -56.1900m
                                });
                        });

                    b.Navigation("DireccionPostal")
                        .IsRequired();

                    b.Navigation("Nombre")
                        .IsRequired();

                    b.Navigation("Ubicacion")
                        .IsRequired();
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.Envios.Envio", b =>
                {
                    b.HasOne("LogicaNegocio.Entidades.Usuarios.Usuario.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogicaNegocio.Entidades.Usuarios.Usuario.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("LogicaNegocio.Vo.Envio.NroTracking", "NroTracking", b1 =>
                        {
                            b1.Property<int>("EnvioId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("NroTracking");

                            b1.HasKey("EnvioId");

                            b1.ToTable("Envios");

                            b1.WithOwner()
                                .HasForeignKey("EnvioId");
                        });

                    b.OwnsOne("LogicaNegocio.Vo.Envio.Peso", "Peso", b1 =>
                        {
                            b1.Property<int>("EnvioId")
                                .HasColumnType("int");

                            b1.Property<decimal>("Value")
                                .HasPrecision(10, 3)
                                .HasColumnType("decimal(10,3)")
                                .HasColumnName("Peso");

                            b1.HasKey("EnvioId");

                            b1.ToTable("Envios");

                            b1.WithOwner()
                                .HasForeignKey("EnvioId");
                        });

                    b.Navigation("Cliente");

                    b.Navigation("Empleado");

                    b.Navigation("NroTracking")
                        .IsRequired();

                    b.Navigation("Peso")
                        .IsRequired();
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.EtapaSeguimiento", b =>
                {
                    b.HasOne("LogicaNegocio.Entidades.Usuarios.Usuario.Empleado", "Empleado")
                        .WithMany()
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("LogicaNegocio.Entidades.Envios.Envio", "Envio")
                        .WithMany()
                        .HasForeignKey("IdEnvio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("LogicaNegocio.Vo.Envio.NroTracking", "NroTracking", b1 =>
                        {
                            b1.Property<int>("EtapaSeguimientoId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("NroTracking");

                            b1.HasKey("EtapaSeguimientoId");

                            b1.ToTable("EtapasSeguimiento");

                            b1.WithOwner()
                                .HasForeignKey("EtapaSeguimientoId");
                        });

                    b.OwnsOne("LogicaNegocio.Vo.EtapaSeguimiento.Comentario", "Comentario", b1 =>
                        {
                            b1.Property<int>("EtapaSeguimientoId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Comentario");

                            b1.HasKey("EtapaSeguimientoId");

                            b1.ToTable("EtapasSeguimiento");

                            b1.WithOwner()
                                .HasForeignKey("EtapaSeguimientoId");
                        });

                    b.OwnsOne("LogicaNegocio.Vo.EtapaSeguimiento.Fecha", "Fecha", b1 =>
                        {
                            b1.Property<int>("EtapaSeguimientoId")
                                .HasColumnType("int");

                            b1.Property<DateTime>("Value")
                                .HasColumnType("datetime2")
                                .HasColumnName("Fecha");

                            b1.HasKey("EtapaSeguimientoId");

                            b1.ToTable("EtapasSeguimiento");

                            b1.WithOwner()
                                .HasForeignKey("EtapaSeguimientoId");
                        });

                    b.Navigation("Comentario")
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Envio");

                    b.Navigation("Fecha")
                        .IsRequired();

                    b.Navigation("NroTracking")
                        .IsRequired();
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.Usuarios.Usuario.Usuario", b =>
                {
                    b.OwnsOne("LogicaNegocio.Vo.Usuario.Nombre", "Nombre", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Nombre");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");

                            b1.HasData(
                                new
                                {
                                    UsuarioId = 1,
                                    Value = "Juan"
                                },
                                new
                                {
                                    UsuarioId = 2,
                                    Value = "María"
                                },
                                new
                                {
                                    UsuarioId = 3,
                                    Value = "Carlos"
                                },
                                new
                                {
                                    UsuarioId = 4,
                                    Value = "Fernanda"
                                });
                        });

                    b.OwnsOne("LogicaNegocio.Vo.Usuario.Apellido", "Apellido", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Apellido");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");

                            b1.HasData(
                                new
                                {
                                    UsuarioId = 1,
                                    Value = "Pérez"
                                },
                                new
                                {
                                    UsuarioId = 2,
                                    Value = "Gómez"
                                },
                                new
                                {
                                    UsuarioId = 3,
                                    Value = "Rodríguez"
                                },
                                new
                                {
                                    UsuarioId = 4,
                                    Value = "López"
                                });
                        });

                    b.OwnsOne("LogicaNegocio.Vo.Usuario.Clave", "Clave", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Clave");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");

                            b1.HasData(
                                new
                                {
                                    UsuarioId = 1,
                                    Value = "admin123"
                                },
                                new
                                {
                                    UsuarioId = 2,
                                    Value = "admin123"
                                },
                                new
                                {
                                    UsuarioId = 3,
                                    Value = "cliente123"
                                },
                                new
                                {
                                    UsuarioId = 4,
                                    Value = "cliente123"
                                });
                        });

                    b.OwnsOne("LogicaNegocio.Vo.Usuario.Correo", "Correo", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Correo");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");

                            b1.HasData(
                                new
                                {
                                    UsuarioId = 1,
                                    Value = "juan@gmail.com"
                                },
                                new
                                {
                                    UsuarioId = 2,
                                    Value = "maria@gmail.com"
                                },
                                new
                                {
                                    UsuarioId = 3,
                                    Value = "carlitos@gmail.com"
                                },
                                new
                                {
                                    UsuarioId = 4,
                                    Value = "fernanda@gmail.com"
                                });
                        });

                    b.OwnsOne("LogicaNegocio.Vo.Usuario.Telefono", "Telefono", b1 =>
                        {
                            b1.Property<int>("UsuarioId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Telefono");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuarios");

                            b1.WithOwner()
                                .HasForeignKey("UsuarioId");

                            b1.HasData(
                                new
                                {
                                    UsuarioId = 1,
                                    Value = "099123456"
                                },
                                new
                                {
                                    UsuarioId = 2,
                                    Value = "099654321"
                                },
                                new
                                {
                                    UsuarioId = 3,
                                    Value = "099122555"
                                },
                                new
                                {
                                    UsuarioId = 4,
                                    Value = "099777888"
                                });
                        });

                    b.Navigation("Apellido")
                        .IsRequired();

                    b.Navigation("Clave")
                        .IsRequired();

                    b.Navigation("Correo")
                        .IsRequired();

                    b.Navigation("Nombre")
                        .IsRequired();

                    b.Navigation("Telefono")
                        .IsRequired();
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.Envios.Comun", b =>
                {
                    b.HasOne("LogicaNegocio.Entidades.Agencia", "LugarRetiro")
                        .WithMany()
                        .HasForeignKey("LugarRetiroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LugarRetiro");
                });

            modelBuilder.Entity("LogicaNegocio.Entidades.Envios.Urgente", b =>
                {
                    b.OwnsOne("LogicaNegocio.Vo.Agencia.DireccionPostal", "DireccionPostal", b1 =>
                        {
                            b1.Property<int>("UrgenteId")
                                .HasColumnType("int");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("DireccionPostal");

                            b1.HasKey("UrgenteId");

                            b1.ToTable("Envios");

                            b1.WithOwner()
                                .HasForeignKey("UrgenteId");
                        });

                    b.OwnsOne("LogicaNegocio.Vo.Envio.Entregado", "Entregado", b1 =>
                        {
                            b1.Property<int>("UrgenteId")
                                .HasColumnType("int");

                            b1.Property<bool>("Value")
                                .HasColumnType("bit")
                                .HasColumnName("Entregado");

                            b1.HasKey("UrgenteId");

                            b1.ToTable("Envios");

                            b1.WithOwner()
                                .HasForeignKey("UrgenteId");
                        });

                    b.Navigation("DireccionPostal");

                    b.Navigation("Entregado");
                });
#pragma warning restore 612, 618
        }
    }
}
